### ISSUE TITLE
Bedrock Players are not listed

### ISSUE THREAD

**Issue by pavl21** [Dantevg/WebStats#53]
Java Players are availabale, but Bedrock (GeyserMC) players aren't listed

**Comment by Dantevg** [comment]
Hi, sorry it took me a while to get to your issue. I assume you're specifically missing the PlaceholderAPI data and that any stats from the in-game scoreboard will appear just fine.

Could you check `your-ip:webstats-port/stats.json` to see whether the bedrock players' names and/or stats do appear there? If so, that means the bug is in the web front-end.
Otherwise, here's a custom version of the plugin that includes a command `/webstats debug placeholderplayers`. Please run it to see whether the players are even picked up at all: [WebStats-1.8.3-SNAPSHOT+mc1.18+.jar.zip](https://github.com/Dantevg/WebStats/files/10058422/WebStats-1.8.3-SNAPSHOT%2Bmc1.18%2B.jar.zip)

**Comment by pavl21** [comment]
The Bedrock players are listed in the json and in the placeholder. I just tested.
Here`s the Website: http://leben-mc.de:25571/stats.json

**Comment by Dantevg** [comment]
Thanks for the link. I see that Bedrock players get a `.` before their name, and the web front-end automatically filters out names that are not valid for Java edition. (It does that to eliminate noise from non-player scoreboard entries.)

I'll add an option to `config.yml` to specify the Bedrock prefix.

**Comment by pavl21** [comment]
Thanks.

**Comment by Dantevg** [comment]
Just implemented a fix. I think it should work but I don't have a Geyser server to test this on. Here's the jar: [WebStats-1.8.3-SNAPSHOT+mc1.18+.jar.zip](https://github.com/Dantevg/WebStats/files/10149012/WebStats-1.8.3-SNAPSHOT%2Bmc1.18%2B.jar.zip). Please let me know whether it works (or close the issue) 🙂

**Comment by pavl21** [comment]
I've tested, and it's not fixed. I have tested this here: http://45.89.143.118:25571/stats.json with the new Version you send.

**Comment by Dantevg** [comment]
Whoops, forgot to actually update the web files in the jar, sorry! Here's the new version: [WebStats-1.8.3-SNAPSHOT+mc1.18+.jar.zip](https://github.com/Dantevg/WebStats/files/10149416/WebStats-1.8.3-SNAPSHOT%2Bmc1.18%2B.jar.zip)

**Comment by pavl21** [comment]
Now, the web folder is empty. (After delete the exiting folder from the Plugin)

**Comment by Dantevg** [comment]
WebStats does not itself add files to that folder. In the last jar download I just added the `WebStats-dist.js` and `WebStats-dist.js.map` files to the jar (that's what I meant with web files), so you could have kept all other files in the web folder and it should work.
