### ISSUE TITLE
index.html not being generated?

### ISSUE THREAD

**Issue by Sloth-on-meth** [Dantevg/WebStats#61]
the 'web' folder is empty for me. getting 'No connection to server. Maybe the server is offline, or the 'host' setting in index.html is incorrect.'

**Comment by Dantevg** [comment]
WebStats stores the files it serves (`index.html`, `style.css` and `WebStats-dist.js`) inside the jar. The `web` folder is for when you want to override these files.

If your server is behind a reverse proxy (or something like bungeecord), try the latest pre-release. It should fix reverse-proxy/bungeecord support but I haven't made a full release for it yet.
Otherwise, are there any errors in the server console? Can you access `ip:port/stats.json`? (where `ip:port` is the location of the WebStats webpage)

**Comment by Dantevg** [comment]
Closing for now, feel free to reopen if you keep having this issue.
