### ISSUE TITLE
Column ordering does not seem to work

### ISSUE THREAD

**Issue by Olen** [Dantevg/WebStats#70]
It could just be me, but I can't get the column-ordering to work.

I have changed config.yml and added:
```
tables:
    #columns: []
    columns: ['Level', 'XP', 'Total Kills', 'Death Count']
```
These are the display names, but I have also tried the objective name (if I understand this correctly).  E.g:

`> scoreboard objectives add deathCount deathCount "Death Count"`

And then use `deathCount` in the config:

```
    columns: ['level', 'XP', 'totalKills', 'deathCount']
```

But it always displays them in alphabetical order:

![image](https://github.com/Dantevg/WebStats/assets/203184/92eb241c-7e7b-4cb3-ac77-0edb6d0d73d0)

Another little issue there is that it would be nice if empty columns could show up.  It was very confusing when I started setting up this plugin that I did not see anything.

**Comment by Dantevg** [comment]
I think you are missing a `-` like so:
```yaml
tables:
  - # (some comments are here probably)
    columns: ['Level', 'XP', 'Total Kills', 'Death Count']
```

That `-` is what makes `tables` a list of "objects" with columns instead of a single "object" with columns.

For the columns, you cannot enter the scoreboard objective name, that is only possible in `objectives`.

Thanks for the empty column suggestion! That sounds like a good idea to reduce confusion and I'll add it in the next release.

**Comment by Olen** [comment]
Ah, thanks.  I cleaned up the file a bit and missed that it was supposed to be a list.

Works perfectly with the added "-"
